### ISSUE TITLE
Deprecated selector in `autocomplete-kdb-q/styles/autocomplete-kdb-q.less`

### ISSUE THREAD

**Issue by seizetheday** [quintanar401/autocomplete-kdb-q#3]
In `autocomplete-kdb-q/styles/autocomplete-kdb-q.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .atom-kdb-definition-marker div` => `atom-text-editor.editor .atom-kdb-definition-marker div`

* `atom-text-editor::shadow .atom-kdb-definition-marker.active div` => `atom-text-editor.editor .atom-kdb-definition-marker.active div`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by quintanar401** [comment]
fixed
